//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDRA_TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int IdProduto { get; set; }
        public string Descricao { get; set; }
        public int Qntd { get; set; }
        public System.DateTime DataFab { get; set; }
        public double Preco { get; set; }
    }
}
