//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace INDRA_TEST.Models
{
    
    
    public partial class Venda
    {
        public Venda()
        {
            this.VendaProduto = new HashSet<VendaProduto>();
        }
    
        public int IdVenda { get; set; }
        public double ValorTotal { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual ICollection<VendaProduto> VendaProduto { get; set; }
    }
}
