//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDRA_TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendaProduto
    {
        public int IdVendaProduto { get; set; }
        public int Qntd { get; set; }
        public int Produto_IdProduto { get; set; }
        public int Venda_IdVenda { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Venda Venda { get; set; }
    }
}
